FROM debian:bullseye

RUN apt update && \
apt install -y mariadb-server netcat && \
apt clean && \
rm -rf /var/lib/apt/lists/*

EXPOSE 3306

RUN mkdir -p /run/mysqld && chown -R  mysql:mysql /run/mysqld && chmod 777 /run/mysqld

COPY entrypoint.sh /docker-entrypoint-initdb.d/
COPY my.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

ENTRYPOINT ["sh", "/docker-entrypoint-initdb.d/entrypoint.sh"]

CMD [ "mariadbd", "--datadir=/var/lib/mysql"]