FROM debian:bullseye

RUN apt update && \
    apt install -y nginx && \
    apt install -y openssl && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/ssl/private /etc/ssl/certs && \
    openssl req -x509 -nodes -days 365 \
    -newkey rsa:2048 \
    -keyout /etc/ssl/private/nginx.key \
    -out /etc/ssl/certs/nginx.crt \
    -subj "/C=FR/ST=Paris/L=Paris/O=42/OU=Inception/CN=mszymcza.42.fr" && \
    chmod 777 /etc/ssl/private/nginx.key /etc/ssl/certs/nginx.crt

COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
